_target_: src.models.DiffusionModule

defaults:
  - net: unet3d.yaml
  - sampler: ddpm.yaml

autoencoder_ckpt_path: ""

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.00005

scheduler: !!null
  # _target_: src.utils.lr_scheduler.LambdaWarmUpScheduler3
  # warm_up_steps: 5000

use_ema: true