_target_: src.models.ds_classification_module.ClassificationModule

net:
  _target_: vit_pytorch.ViT
  image_size: 32
  patch_size: 4
  num_classes: 2
  dim: 1024
  depth: 6
  heads: 16
  mlp_dim: 2048
  dropout: 0.1
  emb_dropout: 0.1

autoencoder_ckpt_path: ""
criterion:
  _target_: src.models.components.loss_function.cross_entropy.CrossEntropyLoss
  weight: [50.0, 1.0]

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# compile model for faster training with pytorch 2.0
compile: false
