_target_: src.models.segmentation_module.SegmentationModule

defaults:
  - net: downstream_unet3d.yaml
  - criterion: dice_loss.yaml
# net:
#   autoencoder_path: ""

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# loss_weight: [0.02, 1.0]
loss_weight: [1, 500]
# compile model for faster training with pytorch 2.0
# compile: false
