_target_: src.models.ClassificationModule

net:
  _target_: vit_pytorch.vit_3d.ViT
  image_size: 32          # image size
  frames: 32            # number of frames
  image_patch_size: 16     # image patch size
  frame_patch_size: 16      # frame patch size
  num_classes: 2
  dim: 1024
  depth: 6
  heads: 8
  mlp_dim: 2048
  dropout: 0.1
  emb_dropout: 0.1

autoencoder_ckpt_path: ""

loss_weight: [1.0, 0.05]

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# compile model for faster training with pytorch 2.0
compile: false
