_target_: src.models.segmentation_module.SegmentationModule

defaults:
  - net: origin_unetplusplus.yaml
  - criterion: bce_lovasz.yaml

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
