_target_: src.models.segmentation_ae_module.SegmentationAEModule

defaults:
  - net: origin_unetplusplus.yaml
  - criterion: cross_entropy.yaml

autoencoder_path: ""

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

use_ema: False
