defaults:
  - model_checkpoint.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - log_image.yaml
  - log_metrics.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/ssim"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

log_metrics:
  ssim:
    _target_: torchmetrics.image.StructuralSimilarityIndexMeasure
    data_range: 2.0
  psnr:
    _target_: torchmetrics.image.PeakSignalNoiseRatio
    data_range: 2.0
  # fid:
  #   _target_: torchmetrics.image.FrechetInceptionDistance
  #   feature: 2048
  #   normalize: True
  # is:
  #   _target_: torchmetrics.image.InceptionScore
  #   feature: 2048
  #   normalize: True

model_summary:
  max_depth: -1