defaults:
  - segmentation_metrics
  - classification_metrics
  - model_checkpoint
  - model_summary
  - rich_progress_bar
  # - image_logger
  - log_image.yaml
  # - video_logger
  - mask2d_logger
  - log_metrics.yaml
  - _self_
