# @package _global_

defaults:
  - _self_
  - data: lidc
  - model: downstream_classification
  - callbacks: default
  - logger: null # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

  - experiment: null

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
# ckpt_path: "/work/hpc/pgl/lung-diffusion/logs/train_classification/runs/ds_resnet18/lung-thesis/11jhko3b/checkpoints/epoch=0-step=260.ckpt"
# ckpt_path: "/work/hpc/pgl/lung-diffusion/logs/train_classification/runs/ds_resnet50/lung-thesis/1qgmt6dq/checkpoints/epoch=61-step=16120.ckpt"
ckpt_path: "/work/hpc/pgl/lung-diffusion/logs/train_autoencoder/runs/swin_cls_seg_soft_dice_v2/lung-thesis/oruicgly/checkpoints/epoch=36-step=76812.ckpt"
