_target_: src.models.components.segmentation.origin_unetplusplus.UNetPlusPlus3D

in_channels: 1
base_channels: 16
n_classes: 2
number_unet: 4
conv_layer: Conv3d
norm_layer: InstanceNorm3d
activate_layer: LeakyReLU
transpconv_layer: ConvTranspose3d
conv_kwargs:
  kernel_size: 3
  padding: 1
norm_kwargs:
  eps: 1e-05
  affine: true
activate_kwargs:
  negative_slope: 0.01
  inplace: true
transpconv_kwargs:
  stride: 2
  kernel_size: 2
  bias: false
